spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  application:
    name: reggie
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB


mybatis-plus:
  global-config:
    db-config:
      id-type: auto

reggie:
  image:
    path: D:/BaiduNetdiskDownload/img